"""phase1 authoritative schema

Revision ID: 0001
Revises:
Create Date: 2026-09-15 23:01:12.959295
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "component",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("domain", sa.String(length=40), nullable=False),
        sa.Column("asil", sa.String(length=8), nullable=False),
        sa.Column("supplier", sa.String(length=80), nullable=False),
        sa.Column("fictional", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "software_build",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=False),
        sa.Column("build_family", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sequence"),
    )
    op.create_table(
        "test_case",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("test_family", sa.String(length=40), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("duration_min", sa.Float(), nullable=False),
        sa.Column("automated", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vehicle_variant",
        sa.Column("id", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("powertrain", sa.String(length=20), nullable=False),
        sa.Column("market", sa.String(length=20), nullable=False),
        sa.Column("features", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "build_change",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("build_id", sa.String(length=20), nullable=False),
        sa.Column("target_type", sa.String(length=12), nullable=False),
        sa.Column("target_id", sa.String(length=40), nullable=False),
        sa.Column("change_kind", sa.String(length=30), nullable=False),
        sa.Column("magnitude", sa.Float(), nullable=False),
        sa.Column("new_revision", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["software_build.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("build_change", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_build_change_build_id"), ["build_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_build_change_target_id"), ["target_id"], unique=False)

    op.create_table(
        "component_dependency",
        sa.Column("upstream_id", sa.String(length=40), nullable=False),
        sa.Column("downstream_id", sa.String(length=40), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["downstream_id"],
            ["component.id"],
        ),
        sa.ForeignKeyConstraint(
            ["upstream_id"],
            ["component.id"],
        ),
        sa.PrimaryKeyConstraint("upstream_id", "downstream_id"),
    )
    op.create_table(
        "requirement",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("fmea_impact", sa.Integer(), nullable=False),
        sa.Column("fmea_occurrence", sa.Integer(), nullable=False),
        sa.Column("fmea_detectability", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_build_id", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_build_id"],
            ["software_build.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "test_component",
        sa.Column("test_id", sa.String(length=20), nullable=False),
        sa.Column("component_id", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["component.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["test_case.id"],
        ),
        sa.PrimaryKeyConstraint("test_id", "component_id"),
    )
    op.create_table(
        "test_execution",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("test_id", sa.String(length=20), nullable=False),
        sa.Column("build_id", sa.String(length=20), nullable=False),
        sa.Column("variant_id", sa.String(length=10), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("verdict", sa.String(length=10), nullable=False),
        sa.Column("duration_min", sa.Float(), nullable=False),
        sa.Column("executed_at", sa.DateTime(), nullable=False),
        sa.Column("requirement_revision", sa.Integer(), nullable=False),
        sa.Column("selected_by", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["software_build.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["test_case.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["vehicle_variant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("test_id", "build_id", "variant_id", "attempt"),
    )
    with op.batch_alter_table("test_execution", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_test_execution_build_id"), ["build_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_test_execution_test_id"), ["test_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_test_execution_variant_id"), ["variant_id"], unique=False)

    op.create_table(
        "test_variant",
        sa.Column("test_id", sa.String(length=20), nullable=False),
        sa.Column("variant_id", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["test_case.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["vehicle_variant.id"],
        ),
        sa.PrimaryKeyConstraint("test_id", "variant_id"),
    )
    op.create_table(
        "defect",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("execution_id", sa.String(length=20), nullable=False),
        sa.Column("component_id", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=20), nullable=False),
        sa.Column("failure_stage", sa.String(length=30), nullable=False),
        sa.Column("signal_signature", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["component.id"],
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["test_execution.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("defect", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_defect_component_id"), ["component_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_defect_execution_id"), ["execution_id"], unique=False)

    op.create_table(
        "requirement_component",
        sa.Column("requirement_id", sa.String(length=20), nullable=False),
        sa.Column("component_id", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["component.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirement.id"],
        ),
        sa.PrimaryKeyConstraint("requirement_id", "component_id"),
    )
    op.create_table(
        "test_requirement",
        sa.Column("test_id", sa.String(length=20), nullable=False),
        sa.Column("requirement_id", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirement.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["test_case.id"],
        ),
        sa.PrimaryKeyConstraint("test_id", "requirement_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_requirement")
    op.drop_table("requirement_component")
    with op.batch_alter_table("defect", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_defect_execution_id"))
        batch_op.drop_index(batch_op.f("ix_defect_component_id"))

    op.drop_table("defect")
    op.drop_table("test_variant")
    with op.batch_alter_table("test_execution", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_execution_variant_id"))
        batch_op.drop_index(batch_op.f("ix_test_execution_test_id"))
        batch_op.drop_index(batch_op.f("ix_test_execution_build_id"))

    op.drop_table("test_execution")
    op.drop_table("test_component")
    op.drop_table("requirement")
    op.drop_table("component_dependency")
    with op.batch_alter_table("build_change", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_build_change_target_id"))
        batch_op.drop_index(batch_op.f("ix_build_change_build_id"))

    op.drop_table("build_change")
    op.drop_table("vehicle_variant")
    op.drop_table("test_case")
    op.drop_table("software_build")
    op.drop_table("component")
    # ### end Alembic commands ###
