"""phase6-8 agentic layer

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-15 23:34:17.079133
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_run",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("actor", sa.String(length=60), nullable=False),
        sa.Column("user_request", sa.Text(), nullable=False),
        sa.Column("build_id", sa.String(length=20), nullable=True),
        sa.Column("variant_id", sa.String(length=10), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("response", sa.Text(), nullable=False),
        sa.Column("clarification_question", sa.Text(), nullable=True),
        sa.Column("model_provider", sa.String(length=40), nullable=False),
        sa.Column("model_name", sa.String(length=80), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("policy_version", sa.String(length=20), nullable=False),
        sa.Column("engine_versions", sa.Text(), nullable=False),
        sa.Column("trace", sa.Text(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "provenance_record",
        sa.Column("seq", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entry_type", sa.String(length=30), nullable=False),
        sa.Column("subject_id", sa.String(length=40), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("seq"),
        sa.UniqueConstraint("hash"),
    )
    with op.batch_alter_table("provenance_record", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_provenance_record_entry_type"), ["entry_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_provenance_record_subject_id"), ["subject_id"], unique=False)

    op.create_table(
        "policy_decision",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=20), nullable=True),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.Column("actor", sa.String(length=60), nullable=False),
        sa.Column("tool_name", sa.String(length=80), nullable=False),
        sa.Column("permission", sa.String(length=60), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("policy_version", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("policy_decision", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_policy_decision_decision"), ["decision"], unique=False)
        batch_op.create_index(batch_op.f("ix_policy_decision_run_id"), ["run_id"], unique=False)

    op.create_table(
        "recommendation",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("run_id", sa.String(length=20), nullable=False),
        sa.Column("build_id", sa.String(length=20), nullable=False),
        sa.Column("variant_id", sa.String(length=10), nullable=False),
        sa.Column("test_id", sa.String(length=20), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("priority_score", sa.Float(), nullable=False),
        sa.Column("estimated_minutes", sa.Float(), nullable=False),
        sa.Column("expected_coverage_gain", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("reasons", sa.Text(), nullable=False),
        sa.Column("evidence_ids", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recommendation", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recommendation_build_id"), ["build_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_recommendation_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_recommendation_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_recommendation_test_id"), ["test_id"], unique=False)

    op.create_table(
        "approval",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("recommendation_id", sa.String(length=20), nullable=False),
        sa.Column("decision", sa.String(length=12), nullable=False),
        sa.Column("reviewer", sa.String(length=60), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("approval", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_approval_recommendation_id"), ["recommendation_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("approval", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approval_recommendation_id"))

    op.drop_table("approval")
    with op.batch_alter_table("recommendation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recommendation_test_id"))
        batch_op.drop_index(batch_op.f("ix_recommendation_status"))
        batch_op.drop_index(batch_op.f("ix_recommendation_run_id"))
        batch_op.drop_index(batch_op.f("ix_recommendation_build_id"))

    op.drop_table("recommendation")
    with op.batch_alter_table("policy_decision", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_policy_decision_run_id"))
        batch_op.drop_index(batch_op.f("ix_policy_decision_decision"))

    op.drop_table("policy_decision")
    with op.batch_alter_table("provenance_record", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provenance_record_subject_id"))
        batch_op.drop_index(batch_op.f("ix_provenance_record_entry_type"))

    op.drop_table("provenance_record")
    op.drop_table("agent_run")
    # ### end Alembic commands ###
